---
title: "`r params$title`"
# author: "Lucy Grigoroff"
date: "`r format(Sys.Date(), '%Y-%m-%d')`" 
output: html_document
params: 
  title: "QC Report"
  data: NULL
  file: NULL
  plateOrder: NULL
  scale: TRUE
---

```{r setup, include=FALSE}
library(htmltools)
knitr::opts_chunk$set(echo = TRUE)

if(is.null(params$data)){
  dae <- makeAAdae(result = params$data, file = params$file)
}else {
  dae <- params$data
}

```

## QC Summary Tables 
```{r pressure1, echo=FALSE}

# Use tagList to collect and render HTML tables properly in a loop
html_output <- tagList()
table_data <- summaryTables(dae = dae, plateOrder = params$plateOrder)

for (table_name in names(table_data[["tables"]])) {
  table <- table_data[["tables"]][[table_name]]
  
  # Add a title for each table
  html_output <- tagAppendChild(html_output, h3(paste("Table for", table_name)))
  
  # Append table to html_output
  if (inherits(table, "gt_tbl")) {
    html_output <- tagAppendChild(html_output, table)  # Append gt table
  } else {
    html_output <- tagAppendChild(html_output, knitr::kable(table, caption = paste("Table for", table_name), format = "html"))
  }
}

# Render all tables at once
html_output
```

## Analyte Plots

```{r pressure2, fig.width = 24, fig.height = 6, echo = FALSE}
scale <- params$scale
plot_data <- suppressMessages(suppressWarnings(plotQC(dae = dae, scale = params$scale, plateOrder = params$plateOrder)))

num_plates <- length(unique(plot_data[[1]]$data$plateID)) 
fig_width <- max(12, num_plates * 3)  # Adjust multiplier as needed
```
<style>
  .superbigimage{
      overflow-x:scroll;
      white-space: nowrap;
  }

  .superbigimage img{
     max-width: none;
  }


</style>

<div class="superbigimage">

```{r plot_it , echo = FALSE, fig.width=fig_width, fig.height=6}

for (i in seq_along(plot_data)) {
print(plot_data[[i]])
  cat("\n\n")
}
```
</div>




